### ISSUE TITLE
Not working in IE8

### ISSUE THREAD

**Issue by forestnight** [mmonkey/google_calendar_events#1]
The script doesn't work with IE8.  The example page will not display the events.

**Comment by mmonkey** [comment]
You maybe able to use a polyfill to make this work. The problem is IE8 doesn't use AJAX, you must use a XDomainRequest. However these types of requests do not handle CORS requests. I am unable to test this at the moment, and can only simply provide you with a link to a polyfill. Add this to the top of your HTML file when testing.

**IE8/IE9 will only work if you are using a secure domain (https) & the polyfill below.**
**This is also NOT a guarantee it will work, I do not have the capability of testing this at the moment.**

Polyfill:
https://github.com/MoonScript/jQuery-ajaxTransport-XDomainRequest

Otherwise IE8 / IE9 is not a supported browser by Microsoft, nor myself. I do try to support it when I can, but in this case, it is beyond the scope of this plugin.
